'use strict'

module.exports = /** @type {import("@cspell/cspell-types").FileSettings} */ ({
  files: ['**/*.*'],
  ignorePaths: [
    '/node_modules',
    '/output',
    'package-lock.json',
  ],
  ignoreWords: [],
  language: 'en-US',
  version: '0.2',
  words: [
    "EVgo's",
    'EVgo',
    'apollographql',
    'bytecode',
    'camelcase',
    'codeceptjs',
    'codegen',
    'commandline',
    'coreutils',
    'dnsutils',
    'doctorwho',
    'evgo',
    'fcms',
    'listbox',
    'mailslurp',
    'networkidle',
    'networkidle0',
    'nslookup',
    'promocode',
    'reportal',
    'reportals',
    'requestfinished',
    'resemblehelper',
    'resemblejs',
    'testid',
    'testrail',
    'wdio',
    'webdriverio',
    'blagoja',
    'hristoski',
    'addnewlocation',
    'plugscore',
    'Coppell',
    'rivian',
    'RIVIAN',
    'stationnew',
    'outletnew',
    'CCSSAE',
    'Chademo',
    'checkall',
    'plugshare',
    'editlocation',
    'searchandfilters',
    'Bitola',
    'dont',
    'Recargo',
    ],
})
